import {IMenu} from '@redux/types';

export const MENU_LIST: IMenu[] = [
  {
    name: 'Menu 1',
    image: require('../assets/images/menu-1.jpg'),
    price: 45,
    ingredients: ['Patates', 'Domates'],
    id: 1,
    count: 1,
  },
  {
    name: 'Menu 2',
    image: require('../assets/images/menu-2.jpg'),
    price: 25,
    ingredients: ['Domates', 'Salatalık'],
    id: 2,
    count: 1,
  },
  {
    name: 'Menu 3',
    image: require('../assets/images/menu-3.jpg'),
    price: 30,
    ingredients: ['Bezelye', 'Havuç'],
    id: 3,
    count: 1,
  },
  {
    name: 'Menu 4',
    image: require('../assets/images/menu-4.jpg'),
    price: 27,
    ingredients: ['Peynir', 'Biber'],
    id: 4,
    count: 1,
  },
  {
    name: 'Menu 5',
    image: require('../assets/images/menu-5.jpg'),
    price: 110,
    ingredients: ['Domates', 'Biber'],
    id: 5,
    count: 1,
  },
  {
    name: 'Menu 6',
    image: require('../assets/images/menu-6.jpg'),
    price: 68,
    ingredients: ['Patates', 'Domates'],
    id: 6,
    count: 1,
  },
  {
    name: 'Menu 7',
    image: require('../assets/images/menu-7.jpg'),
    price: 50,
    ingredients: ['Pirinç', 'Nohut'],
    id: 7,
    count: 1,
  },
  {
    name: 'Menu 8',
    image: require('../assets/images/menu-8.jpg'),
    price: 12,
    ingredients: ['Soğan', 'Biber'],
    id: 8,
    count: 1,
  },
  {
    name: 'Menu 9',
    image: require('../assets/images/menu-9.jpg'),
    price: 80,
    ingredients: ['Kabak', 'Biber'],
    id: 9,
    count: 1,
  },
  {
    name: 'Menu 10',
    image: require('../assets/images/menu-10.jpg'),
    price: 85,
    ingredients: ['Ispanak', 'Biber'],
    id: 10,
    count: 1,
  },
];
